import java.util.Scanner;
import java.lang.Math;

class Main {
    public static Scanner scanner = new Scanner(System.in);
    public static void main(String[] args) {
        // JAVA HAS THE VALUE OF PI BUILT IN YOU IDIOTS JUST LET ME USE IT AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        final double pi = 3.14;
        System.out.println("Enter the radius:");
        double radi = scanner.nextDouble();
        System.out.println("A = " + (Math.pow(radi,2) * pi ) * 10 / 10 + " units ^2");
        System.out.println("C = " + (2 * radi * pi ) * 10 / 10 + " units");
    }
}
